/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#7e7576",
        "surface-container-highest": "#d3e3ff",
        "on-tertiary-fixed-variant": "#00458f",
        "surface-container-low": "#eff4ff",
        "primary": "#000000",
        "tertiary-container": "#001b3f",
        "secondary": "#016d35",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#001b3f",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "secondary-container": "#9bf7af",
        "primary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#00210c",
        "surface-tint": "#5e5e5e",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf6",
        "on-surface-variant": "#4c4546",
        "on-secondary-container": "#0f743b",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e3ff",
        "primary-container": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "on-secondary": "#ffffff",
        "surface": "#f8f9ff",
        "primary-fixed-dim": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005226",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dde9ff",
        "tertiary-fixed-dim": "#abc7ff",
        "background": "#f8f9ff",
        "secondary-fixed-dim": "#7fda95",
        "on-tertiary-container": "#4d83db",
        "on-error-container": "#93000a",
        "inverse-surface": "#213146",
        "tertiary": "#000000",
        "on-primary-container": "#848484",
        "tertiary-fixed": "#d7e3ff",
        "outline-variant": "#cfc4c5",
        "on-error": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "secondary-fixed": "#9bf7af"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "xs": "0.125rem",
        "sm": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "1rem",
        "gutter-mobile": "0.5rem",
        "gutter-desktop": "1.25rem",
        "margin": "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem"
      },
      fontFamily: {
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-sm": ["Manrope", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "title-sm": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "label-lg": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "title-md": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
};
